export default {
  MTN_AUCTION_ADDR: process.env.REACT_APP_MTN_AUCTION_ADDR,
  MTN_TOKEN_ADDR: process.env.REACT_APP_MTN_TOKEN_ADDR,
  MTN_PUBLIC_NODE_URL: process.env.REACT_APP_MTN_PUBLIC_NODE_URL,
  MTN_API_URL: process.env.REACT_APP_MTN_API_URL,
  WS_AUCTION_STATUS_TOPIC: process.env.REACT_APP_WS_AUCTION_STATUS_TOPIC,
  SECURE_STORAGE_KEY: process.env.REACT_APP_SECURE_STORAGE_KEY
};
