export default {
  WS_AUCTION_STATUS_TOPIC: process.env.REACT_APP_WS_AUCTION_STATUS_TOPIC,
  MTN_PUBLIC_NODE_URL: process.env.REACT_APP_MTN_PUBLIC_NODE_URL,
  MTN_AUCTION_ADDR: process.env.REACT_APP_MTN_AUCTION_ADDR,
  MTN_TOKEN_ADDR: process.env.REACT_APP_MTN_TOKEN_ADDR,
  MTN_API_URL: process.env.REACT_APP_MTN_API_URL
}
